# Generated by Django 4.0.4 on 2022-05-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_report',
            name='submittedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
